name: tokoku
description: "Flutter e-commerce app using Fake Store API."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  auth_repo:
    path: packages/auth_repo
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  formz: ^0.6.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  shop_repo:
    path: packages/shop_repo

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/
