name: fake_store_api
description: "Fake Store API package"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.4
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  test: ^1.24.9
  mockito: ^5.4.3

flutter:
  