name: auth_repo
description: "Tokoku authentication repository"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  fake_store_api:
    path: ../fake_store_api
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  test: ^1.24.9

flutter: